config/routes.rb
# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root to: 'guests/index#index'

  scope "(:locale)" do
    devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords" }
  end

  # Guests controllers
  scope "(:locale)", module: 'guests', as: 'guests', locale: /ru/ do
    root to: 'index#index', as: :locale_root
    resources :houses, only: %i[show index]
    get :about, to: 'about#index'
  end

  # Admin controllers
  scope module: 'admin' do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'report/bookings', to: 'reports#bookings'
    get 'report/balance', to: 'reports#balance'
    get 'report/salary', to: 'reports#salary'
    get 'report/income', to: 'reports#income'
    get 'reports', to: 'reports#index'
    resources :notifications, only: [:destroy]
    resources :water_usages
    get 'users/get_houses', to: 'users#get_houses' # , as: 'get_houses'
    get 'users/inactive', to: 'users#inactive'
    # get 'documents/reimbersment', to: 'documents#reimbersment', as: 'tmp_reimbersment'
    # get 'documents/statement', to: 'documents#statement', as: 'tmp_statement'
    resource :documents, only: [:show] do
      get :prepare
      get :design_agreement_preview
      get :reimbersment
      get :statement
      get :invoice
      get :receipt
    end
    resources :house_groups
    delete 'transaction_file', to: 'transaction_files#destroy'
    delete 'transaction_file_tmp', to: 'transaction_files#destroy_tmp'
    get 'transaction_file_download', to: 'transaction_files#download'
    get 'transaction_file_toggle_show', to: 'transaction_files#toggle_show'
    get 'transaction_files', to: 'transaction_files#index'
    get 'transaction_warnings', to: 'transactions#warnings'
    get 'transaction_raw_for_acc', to: 'transactions#raw_for_acc'
    get 'transaction_raw', to: 'transactions#raw'
    get 'jobs/index_new', to: 'jobs#index_new', as: 'jobs_new'
    get 'laundry', to: 'jobs#laundry', as: 'laundry'
    patch 'jobs/:id/update_laundry', to: 'jobs#update_laundry', as: 'update_laundry'
    get 'jobs/job_order', to: 'jobs#job_order', as: 'job_order'
    resources :jobs
    resources :job_types, except: :show
    post 'job_messages', to: 'job_messages#create'
    delete 'job_message', to: 'job_messages#destroy'
    get 'logs', to: 'logs#index'
    # get 'test', to: 'pages#test'
    resources :locations, except: :show
    resources :options, except: :show
    # get 'owner', to: 'admin#index', as: 'owner'
    get 'transactions/all_clients', to: 'transactions#all_clients', as: 'all_clients'
    resources :transactions, except: [:show]
    get 'transactions_docs', to: 'transactions#docs', as: 'transactions_docs'
    post 'transactions/update_invoice_ref', to: 'transactions#update_invoice_ref', as: 'update_invoice_ref'
    get 'balance', to: 'transactions#index', as: 'balance_front'
    resources :transaction_types
    get '/employees/list_for_job', to: 'employees#list_for_job'
    resources :employees
    resources :empl_types
    get '/transfers/:number/confirmed', to: 'transfers#confirmed', as: 'supplier_confirm_transfer'
    get '/transfers/:number/canceled', to: 'transfers#canceled', as: 'supplier_cancel_transfer'
    get '/transfers/supplier', to: 'transfers#index_supplier', as: 'transfers_supplier'
    resources :houses, path: 'admin_houses', as: 'admin_houses' do
      resources :prices, only: [:index]
      resources :photos, only: %i[index new destroy update] do
        put 'sort', on: :member
        delete 'delete_all', on: :collection
      end
      post 'add_duration', to: 'prices#create_duration'
      delete 'delete_duration', to: 'prices#destroy_duration'
      post 'add_season', to: 'prices#create_season'
      delete 'delete_season', to: 'prices#destroy_season'
      resources :bookings, only: %i[index new]
      get 'inactive', to: 'houses#inactive', on: :collection
      get 'export', on: :collection
    end
    post 'booking/new', to: 'bookings#create_front'
    get 'owner/bookings', to: 'bookings#index_front', as: 'bookings_front'
    resources :bookings do
      collection do
        get 'get_reservations'
        get 'get_price'
        get 'canceled'
        get 'timeline'
        get 'timeline_data'
        get 'check_in_out'
        get 'sync'
      end
      member do
        resources :booking_files, only: %i[create destroy], shallow: true
        patch 'update_comment_gr'
      end
    end
    resources :users, except: :create
    post 'create_user', to: 'users#create', as: 'create_user'
    get 'users/:id/password_reset_request', to: 'users#password_reset_request', as: 'password_reset_request'
    get 'test_upload', to: 'houses#test_upload'
    get 'prices/:id/update', to: 'prices#update', as: 'price'
    post 'prices/:house_id/copy_table', to: 'prices#copy_table', as: 'copy_table'
    # get 'owner', to: 'owner#index'
    # get 'tenant', to: 'tenant#index'
    get 'search', to: 'search#index'
    resources :settings
    resources :house_types
    resources :sources, except: :show
    resources :connections, only: %i[create destroy]
    get '/transfers/:id/cancel', to: 'transfers#cancel', as: 'cancel_transfer'
    resources :transfers
    get 'translate', to: "translations#show"
    get 'calendar/ical/:hid', to: 'bookings#ical', as: 'calendar'
  end

  get 'unlock', to: 'dev#unlock' if Rails.env.development?

  # Admin dashboards
  authenticate :user, ->(user) { user.role?('Admin') } do
    # mount GoodJob::Engine => '/admin/activejob'
    resources :uploads_tests # TODO: Remove after #353
    mount MaintenanceTasks::Engine => "/admin/maintenance_tasks"
  end

  # Errors
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*unmatched", to: "errors#not_found", via: :all, constraints: lambda { |req|
    req.path.exclude? '/files'
  }
end
# rubocop:enable

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::AdminController
  before_action :get_house
  before_action :get_photo, only: %i[update sort destroy]


  # @route GET /admin_houses/:admin_house_id/photos (admin_house_photos)
  def index
    authorize! with: Admin::PhotoPolicy
    @photos = @house.photos.rank(:position)
    @s3_direct_post = S3_BUCKET.presigned_post(key: "house_photos/#{@house.number}/${filename}",
                                               success_action_status: '201', acl: 'public-read')
  end

  # @route PUT /admin_houses/:admin_house_id/photos/:id/sort (sort_admin_house_photo)
  def sort
    authorize! with: Admin::PhotoPolicy
    @photo.update(position_position: params[:position])
    head :ok
  end

  # @route GET /admin_houses/:admin_house_id/photos/new (new_admin_house_photo)
  def new
    authorize! with: Admin::PhotoPolicy
    url = params[:photo_url]
    preview = params[:preview]
    render json: { status: 'duplicate' } and return if HousePhoto.find_by(url:)

    photo = @house.photos.create!(url:, title_en: '', title_ru: '')
    # If preview is empty set it to first uploaded image
    @house.update(image: url) unless @house.image.present?
    file_name = photo.url.match(%r{^.*/(.*)$})
    render json: { status: :ok, id: photo.id, file_name: file_name[1] } and return
  end

  # @route PATCH /admin_houses/:admin_house_id/photos/:id (admin_house_photo)
  # @route PUT /admin_houses/:admin_house_id/photos/:id (admin_house_photo)
  def update
    authorize! with: Admin::PhotoPolicy
    @photo.update(house_photo_params)
    if params[:commit] == "Use as default"
      @photo.house.update(image: @photo.url)
      redirect_to admin_house_photos_path(@house.number) and return
    end
    render json: { status: :ok }
  end

  # @route DELETE /admin_houses/:admin_house_id/photos/:id (admin_house_photo)
  def destroy
    authorize! with: Admin::PhotoPolicy
    S3_BUCKET.object(@photo.key).delete
    S3_BUCKET.object(@photo.thumb_key).delete
    @photo.destroy
    respond_to do |format|
      format.js
    end
  end

  # @route DELETE /admin_houses/:admin_house_id/photos/delete_all (delete_all_admin_house_photos)
  def delete_all
    authorize! with: Admin::PhotoPolicy
    S3_BUCKET.objects({ prefix: "house_photos/#{@house.number}" }).batch_delete!
    @house.photos.destroy_all
    @house.update(image: nil)
    redirect_to admin_house_photos_path(@house.number)
  end

  private

  def get_house
    @house = House.find_by(number: params[:admin_house_id])
  end

  def get_photo
    @photo = HousePhoto.find(params[:id])
  end

  def house_photo_params
    params.require(:house_photo).permit(:title_en, :title_ru)
  end
end

app/views/admin/photos/_house_photo.html.erb
<li data-sortable-id="<%= house_photo.id %>" data-sortable-update-url="<%= sort_admin_house_photo_path(house.number, house_photo.id) %>">
  <%= form_with(model: house_photo,
                url: admin_house_photo_path(house.number, house_photo),
                method: :patch,
                id: "form_edit_photo_id_#{house_photo.id}") do |f| %>
    <div class="row photo_row mb-3" id="photo_id_<%= house_photo.id %>">
      <i class='col-md-1 bi bi-list'></i>
      <div class="col-md-2 photo_thumb">
        <img src="<%= house_photo.thumb %>" class='img-fluid mb-1' />
      </div>
      <div class="col-md-7 photo_titles">
        <%= f.text_field :title_en, placeholder: 'Title', class: 'form-control mb-1 photo_title_input', data: {photo_id: house_photo.id} %>
        <%= f.text_field :title_ru, placeholder: 'Подпись', class: 'form-control mb-1 photo_title_input', data: {photo_id: house_photo.id} %>
      </div>
      <div class="col-md-2 photo_actions text-right">
        <%#= f.submit 'Update', class: 'btn btn-primary btn-sm btn-block' %>
        <%= f.submit 'Use as default', class: 'btn btn-primary btn-sm btn-block mt-md-1', tabindex: "-1", method: :patch %>
        <%= link_to 'Delete', admin_house_photo_path(house.number, house_photo), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm btn-block mt-md-1', role: 'button', tabindex: "-1" %>
      </div>
    </div>
    <div class="text-right">
    </div>
    <hr />
  <% end %>
</li>

app/views/admin/photos/delete.js.erb
$('#photo_id_<%= @photo.id %>').remove()

app/views/admin/photos/destroy.js.erb
$('#photo_id_<%= @photo.id %>').remove()

app/views/admin/photos/index.html.erb
<h1><%= @house.code %> photos</h1>

<div class="row">
  <div class="col-xl-3 mb-2">
    <div class="shadow-sm mb-2 p-2 bg-white border rounded">
      <div id='house_preview'><%= image_tag @house.preview, class: 'img-fluid', id: 'house_preview_img' if @house.preview.present? %></div>
      <div class="actions mt-2 text-right">
        <%#= form.submit 'Save House', class: 'btn btn-primary' %>
        <%= link_to 'Delete all photos', delete_all_admin_house_photos_path(@house.number), remote: false, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm btn-block', role: 'button' %>
        <%= link_to 'Back', admin_houses_path, class: 'btn btn-secondary btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-xl-9">
    <div class="shadow-sm mb-2 p-2 bg-white border rounded">
      <%= form_with(local: true, id: 'photoupload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }) do |form| %>
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="customFile" multiple>
          <label class="custom-file-label" for="customFile">Choose photos</label>
        </div>
        <div class="progress mt-2" style="height:3px;">
          <div class="progress-bar bg-info thumb" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <%= hidden_field_tag 'hid', @house.number %>
      <% end %>
      <div id='photo_previews' class='mt-2'>
        <ul data-controller="sortable">
          <%= render(partial: "house_photo", collection: @photos, locals: {house: @house}) %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="custom-file d-none">
  <input type="file" class="custom-file-input" id="photoupload_thumb" multiple>
  <label class="custom-file-label" for="customFile">Choose file</label>
</div>