config/routes.rb
# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root to: 'guests/index#index'

  scope "(:locale)" do
    devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords" }
  end

  # Guests controllers
  scope "(:locale)", module: 'guests', as: 'guests', locale: /ru/ do
    root to: 'index#index', as: :locale_root
    resources :houses, only: %i[show index]
    get :about, to: 'about#index'
  end

  # Admin controllers
  scope module: 'admin' do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'report/bookings', to: 'reports#bookings'
    get 'report/balance', to: 'reports#balance'
    get 'report/salary', to: 'reports#salary'
    get 'report/income', to: 'reports#income'
    get 'reports', to: 'reports#index'
    resources :notifications, only: [:destroy]
    resources :water_usages
    get 'users/get_houses', to: 'users#get_houses' # , as: 'get_houses'
    get 'users/inactive', to: 'users#inactive'
    # get 'documents/reimbersment', to: 'documents#reimbersment', as: 'tmp_reimbersment'
    # get 'documents/statement', to: 'documents#statement', as: 'tmp_statement'
    resource :documents, only: [:show] do
      get :prepare
      get :design_agreement_preview
      get :reimbersment
      get :statement
      get :invoice
      get :receipt
    end
    resources :house_groups
    delete 'transaction_file', to: 'transaction_files#destroy'
    delete 'transaction_file_tmp', to: 'transaction_files#destroy_tmp'
    get 'transaction_file_download', to: 'transaction_files#download'
    get 'transaction_file_toggle_show', to: 'transaction_files#toggle_show'
    get 'transaction_files', to: 'transaction_files#index'
    get 'transaction_warnings', to: 'transactions#warnings'
    get 'transaction_raw_for_acc', to: 'transactions#raw_for_acc'
    get 'transaction_raw', to: 'transactions#raw'
    get 'jobs/index_new', to: 'jobs#index_new', as: 'jobs_new'
    get 'laundry', to: 'jobs#laundry', as: 'laundry'
    patch 'jobs/:id/update_laundry', to: 'jobs#update_laundry', as: 'update_laundry'
    get 'jobs/job_order', to: 'jobs#job_order', as: 'job_order'
    resources :jobs
    resources :job_types, except: :show
    post 'job_messages', to: 'job_messages#create'
    delete 'job_message', to: 'job_messages#destroy'
    get 'logs', to: 'logs#index'
    # get 'test', to: 'pages#test'
    resources :locations, except: :show
    resources :options, except: :show
    # get 'owner', to: 'admin#index', as: 'owner'
    get 'transactions/all_clients', to: 'transactions#all_clients', as: 'all_clients'
    resources :transactions, except: [:show]
    get 'transactions_docs', to: 'transactions#docs', as: 'transactions_docs'
    post 'transactions/update_invoice_ref', to: 'transactions#update_invoice_ref', as: 'update_invoice_ref'
    get 'balance', to: 'transactions#index', as: 'balance_front'
    resources :transaction_types
    get '/employees/list_for_job', to: 'employees#list_for_job'
    resources :employees
    resources :empl_types
    get '/transfers/:number/confirmed', to: 'transfers#confirmed', as: 'supplier_confirm_transfer'
    get '/transfers/:number/canceled', to: 'transfers#canceled', as: 'supplier_cancel_transfer'
    get '/transfers/supplier', to: 'transfers#index_supplier', as: 'transfers_supplier'
    resources :houses, path: 'admin_houses', as: 'admin_houses' do
      resources :prices, only: [:index]
      resources :photos, only: %i[index new destroy update] do
        put 'sort', on: :member
        delete 'delete_all', on: :collection
      end
      post 'add_duration', to: 'prices#create_duration'
      delete 'delete_duration', to: 'prices#destroy_duration'
      post 'add_season', to: 'prices#create_season'
      delete 'delete_season', to: 'prices#destroy_season'
      resources :bookings, only: %i[index new]
      get 'inactive', to: 'houses#inactive', on: :collection
      get 'export', on: :collection
    end
    post 'booking/new', to: 'bookings#create_front'
    get 'owner/bookings', to: 'bookings#index_front', as: 'bookings_front'
    resources :bookings do
      collection do
        get 'get_reservations'
        get 'get_price'
        get 'canceled'
        get 'timeline'
        get 'timeline_data'
        get 'check_in_out'
        get 'sync'
      end
      member do
        resources :booking_files, only: %i[create destroy], shallow: true
        patch 'update_comment_gr'
      end
    end
    resources :users, except: :create
    post 'create_user', to: 'users#create', as: 'create_user'
    get 'users/:id/password_reset_request', to: 'users#password_reset_request', as: 'password_reset_request'
    get 'test_upload', to: 'houses#test_upload'
    get 'prices/:id/update', to: 'prices#update', as: 'price'
    post 'prices/:house_id/copy_table', to: 'prices#copy_table', as: 'copy_table'
    # get 'owner', to: 'owner#index'
    # get 'tenant', to: 'tenant#index'
    get 'search', to: 'search#index'
    resources :settings
    resources :house_types
    resources :sources, except: :show
    resources :connections, only: %i[create destroy]
    get '/transfers/:id/cancel', to: 'transfers#cancel', as: 'cancel_transfer'
    resources :transfers
    get 'translate', to: "translations#show"
    get 'calendar/ical/:hid', to: 'bookings#ical', as: 'calendar'
  end

  get 'unlock', to: 'dev#unlock' if Rails.env.development?

  # Admin dashboards
  authenticate :user, ->(user) { user.role?('Admin') } do
    # mount GoodJob::Engine => '/admin/activejob'
    resources :uploads_tests # TODO: Remove after #353
    mount MaintenanceTasks::Engine => "/admin/maintenance_tasks"
  end

  # Errors
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*unmatched", to: "errors#not_found", via: :all, constraints: lambda { |req|
    req.path.exclude? '/files'
  }
end
# rubocop:enable

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id             :bigint           not null, primary key
#  before         :string
#  closed         :date
#  collected      :date
#  comment        :text
#  job            :text
#  paid_by_tenant :boolean          default(FALSE), not null
#  plan           :date
#  price          :integer
#  rooms          :integer
#  sent           :date
#  status         :integer          default("inbox")
#  time           :string
#  urgent         :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  booking_id     :bigint
#  creator_id     :bigint           not null
#  employee_id    :bigint
#  house_id       :bigint
#  job_type_id    :bigint           not null
#  user_id        :bigint
#
# Indexes
#
#  index_jobs_on_booking_id   (booking_id)
#  index_jobs_on_creator_id   (creator_id)
#  index_jobs_on_employee_id  (employee_id)
#  index_jobs_on_house_id     (house_id)
#  index_jobs_on_job_type_id  (job_type_id)
#  index_jobs_on_status       (status)
#  index_jobs_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (booking_id => bookings.id)
#  fk_rails_...  (creator_id => users.id)
#  fk_rails_...  (employee_id => employees.id)
#  fk_rails_...  (house_id => houses.id)
#  fk_rails_...  (job_type_id => job_types.id)
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  enum status: {  inbox: 0, in_progress: 1, done: 2, paused: 3,
                  cancelled: 4, archived: 5 }

  belongs_to :job_type
  belongs_to :user, optional: true
  belongs_to :creator, class_name: 'User'
  belongs_to :booking, optional: true
  belongs_to :house, optional: true
  belongs_to :employee, optional: true
  has_many :job_messages, dependent: :destroy
  has_many :job_tracks, dependent: :destroy
  # validates :plan, presence: true
end

app/models/job_type.rb
# == Schema Information
#
# Table name: job_types
#
#  id             :bigint           not null, primary key
#  code           :string
#  color          :string
#  for_house_only :boolean
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class JobType < ApplicationRecord
  has_many :jobs, dependent: :destroy
  has_and_belongs_to_many :empl_types
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::AdminController
  before_action :set_job, only: %i[show edit update update_laundry destroy]
  after_action :system_message_create, only: [:create]
  after_action :system_message_update, only: [:update]

  # @route GET /jobs (jobs)
  def index
    authorize!
    @job = Job.new
    @status = params[:status]
    if current_user.role? :admin
      jt_id = JobType.find_by(name: 'For management').id
      @jobs = Job.where(job_type_id: jt_id).order(updated_at: :desc)
    else
      @jobs = current_user.jobs.order(updated_at: :desc)
    end
  end

  # @route GET /jobs/index_new (jobs_new)
  def index_new
    authorize!
    maids = EmplType.find_by(name: 'Maids').employees.ids
    @jobs = Job.where(closed: nil, employee_id: maids).order(:plan)
    # @jobs = Job.where(closed: nil).order(:plan)
    @for = :maids
    render :index
  end

  # @route GET /laundry (laundry)
  def laundry
    authorize!
    from = params[:from]
    to = params[:to]
    if !from.present? && !to.present?
      @laundry = Job.joins(:job_type).where('job_types.code IN (?,?,?) AND (
                                          collected IS NULL OR
                                          sent IS NULL OR
                                          rooms IS NULL OR
                                          price IS NULL)', 'B', 'X', 'L')
        .order(:plan)
    elsif (from.present? && !to.present?) || (!from.present? && to.present?)
      @error_message = "Both dates should be selected / ควรเลือกวันที่ทั้งสอง"
      @laundry = Job.joins(:job_type).where('job_types.code IN (?,?,?) AND (
                                          collected IS NULL OR
                                          sent IS NULL OR
                                          rooms IS NULL OR
                                          price IS NULL)', 'B', 'X', 'L')
        .order(:plan)
    elsif from.present? && to.present?
      from = from.to_date
      to = to.to_date
      @laundry = Job.joins(:job_type).where('job_types.code IN (?,?,?) AND
                            plan >= ? AND plan <= ?', 'B', 'X', 'L', from, to)
        .order(:plan)

    end
  end

  # @route GET /jobs/job_order (job_order)
  def job_order
    authorize!
    if !params[:from].present? || !params[:to].present?
      # need to return error message
    elsif params[:from].present? && params[:to].present?
      from = params[:from].to_date
      to = params[:to].to_date
    end
    jobs_raw = []
    if params[:house].present?
      house = params[:house]
      jobs_raw = House.find_by(number: house).jobs
        .where('plan >= ? AND plan <= ?', from, to)
        .order(:plan, :time)
    else
      hidden_houses1 = hidden_houses2 = []
      hidden_houses1 = params[:hidden_houses].split(',').reject(&:empty?)
      hidden_houses2 = House.where(house_group_id: params[:hidden_groups]).ids unless params[:hidden_groups].nil?
      hidden_houses = (hidden_houses1 + hidden_houses2).uniq
      jobs_raw = Job.where.not(house_id: nil)
        .where.not(house_id: hidden_houses)
        .where('plan >= ? AND plan <= ?', from, to)
        .order(:plan, :time)
    end
    jobs = {}
    date_old = ''
    jobs_raw.each do |j|
      date = j.plan.to_fs(:date)
      if date != date_old
        jobs[date] = []
        # jobs[date]['date'] = date
        # jobs[date]['jobs'] = []
        date_old = date
      end
      jobs[date] << ["#{j.time} #{j.house.code} #{j.job_type.name} #{if j.paid_by_tenant == true
                                                                       '<span class="remarks">[Paid by tenant]</span>'
                                                                     end}"]
    end
    render json: { jobs: jobs }
  end

  # @route GET /jobs/:id (job)
  def show
    authorize!
    @message = JobMessage.new
    @messages = @job.job_messages.last(10)
    # @s3_direct_post = S3_BUCKET.presigned_post(key: "job_messages/#{@job.id}/${filename}", success_action_status: '201', acl: 'public-read')
    @s3_direct_post = S3_BUCKET.presigned_post(
      key: "job_messages/#{@job.id}/${filename}",
      success_action_status: '201',
      acl: 'public-read',
      content_type_starts_with: ""
    )
    trace = @job.job_tracks.where(user_id: current_user.id)
    if trace.any?
      trace.update(visit_time: Time.current)
    else
      @job.job_tracks.create!(user_id: current_user.id, visit_time: Time.current)
    end
  end

  # @route GET /jobs/new (new_job)
  def new
    authorize!
    @job = Job.new
    @houses = House.all.order(:code)
  end

  # @route GET /jobs/:id/edit (edit_job)
  def edit
    authorize!
    @houses = House.all.order(:code)
  end

  # @route POST /jobs (jobs)
  def create
    authorize!
    @job = Job.new(job_params)
    @job.creator_id = current_user.id
    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: 'Job was successfully created.' }
        format.json do
          render json: { job: {
                           id: @job.id,
                           type_id: @job.job_type.id,
                           code: @job.job_type.code,
                           color: @job.job_type.color,
                           time: @job.time,
                           job: @job.job,
                           employee_id: @job.employee_id
                         },
                         cell_id: params[:cell_id] },
                 status: :ok end
      else
        @houses = House.all.order(:code)
        format.html { render :new }
        format.json do
          render json: @job.errors,
                 status: :unprocessable_entity end
      end
    end
  end

  # @route PATCH /jobs/:id (job)
  # @route PUT /jobs/:id (job)
  def update
    authorize!
    if params[:done].present?
      @job_status_toggled = true
      @job.closed = Time.current if params[:done] == 'true'
      @job.closed = nil if params[:done] == 'false'
      @job.save
      return
    end
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_path(@job), notice: 'Job was successfully updated.' }
        format.json { render :index, status: :ok, location: @job }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # @route PATCH /jobs/:id/update_laundry (update_laundry)
  def update_laundry
    authorize!
    @job.update(job_params)
    redirect_to laundry_path
  end

  # @route DELETE /jobs/:id (job)
  def destroy
    authorize! @job
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def system_message_create
    @job.job_messages.create!(sender: current_user,
                              message: "Job created",
                              is_system: 1)
  end

  def system_message_update
    changes = @job.saved_changes
    changes.each do |key, value|
      next if key == "updated_at"

      @job.job_messages.create!(sender: current_user,
                                message: "#{key} changed: #{value[0]} -> #{value[1]}",
                                is_system: 1)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:job_type_id,
                                :user_id,
                                :booking_id,
                                :house_id,
                                :date,
                                :time,
                                :plan,
                                :closed,
                                :job,
                                :comment,
                                :employee_id,
                                :collected,
                                :sent,
                                :rooms,
                                :price,
                                :status,
                                :paid_by_tenant)
  end
end

app/views/admin/jobs/_form.erb
<%= form_with(model: job, local: true) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <div class="form-row job_user">
    <% if current_user.role? :admin %>
      <div class="col-md-2 form-group">
        <%= form.label :Employee %>
        <%= form.select :user_id,
              User.with_role(['Admin', 'Manager', 'Guest relation', 'Accounting']).map {|u| [u.name, u.id]},
              { prompt: 'Select employee' },
              class: "form-control" %>
      </div>
    <% else %>
     <%= form.hidden_field :user_id, value: current_user.id %>
    <% end %>
    <div class="col-md-2 form-group">
      <%= form.label :plan %>
      <%= form.date_field :plan, class: "form-control" %>
    </div>
    <div class="col-md-2 form-group">
      <%= form.label :house %>
      <%= form.select :house_id,
            @houses.map {|h| ["#{h.code} #{'(not for rent)' if h.unavailable}", h.id]},
                      { prompt: 'Select house' }, { class: "form-control",  } %>
    </div>
    <div class="col-md-2 form-group">
      <%= form.label :status %>
      <%= form.select :status,
            [["inbox", "inbox"],["archived", 'archived']],
                      { prompt: 'Select house' }, { class: "form-control",  } %>
    </div>

  </div>
  <div class="form-row">
    <div class="col form-group">
      <%= form.label :job %>
      <%= form.text_field :job, class: "form-control" %>
    </div>
  </div>
  <%= form.hidden_field :job_type_id, value: JobType.find_by(name: 'For management').id %>
  <%= form.submit 'Save', class: "btn btn-primary"  %>
  <%= link_to 'Back', jobs_path, class: "btn btn-secondary"  %>
<% end %>

app/views/admin/jobs/_job_maid.html.erb
<div class="row shadow-sm mb-2 p-2 bg-light rounded">
  <%= job.time %>
  <%= job.booking.house.code if job.booking_id %>
  <%= job.house.code if job.house_id %>
  <%= job.job_type.name %>
</div>

app/views/admin/jobs/_job_managers.html.erb
<% trace = job.job_tracks.find_by(user_id: current_user.id) %>
<% read_status = 'bg-white' %>
<% if (!trace.nil? && trace.visit_time < job.updated_at) || trace.nil? %>
  <% read_status = 'bg-warning' %>
<% end %>
<div class="shadow-sm mb-2 p-2 border rounded <%= read_status %>" id="job_<%= job.id %>">
  <% job_link = '' %>
  <% if current_user.role? :admin %>
    <% job_link = "#{job.user.name}: " if job.user_id %>
  <% end %>
  <% job_link += "#{job.house.code} - " if job.house %>
  <% job_link_plan = "(#{job.plan.to_fs(:date)})" if job.plan.present? %>
  <%= link_to "#{job_link} #{job.job} #{job_link_plan}", job_path(job), class: "open_job_chat text-dark", data: {job_id: job.id} %>
  <% if (job.creator == current_user) || current_user.role?(:admin) %>
    <%= link_to 'Edit', '#', id: "edit_job", data: {job_id: job.id}  %> |
    <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>
<div class="mt-2" style="display: none;" id="form_edit_job_<%= job.id %>">
  <%= form_with(model: job, class: "update_job") do |f| %>
    <%= f.text_area :job, class: 'form-control', row: 2,
      data: {job_id: job.id, field: 'job'} %>
    <%= f.submit 'Save', {  class: "btn btn-primary mt-2"} %>
  <% end %>
</div>

app/views/admin/jobs/_menu.html.erb
<%= link_to 'New Job', new_job_path %> |
<%= link_to 'Active', jobs_path(status: 'active') %> |
<%= link_to 'Postponed', jobs_path(status: 'postponed') %> |
<%= link_to 'Done', jobs_path(status: 'done') %> |
<%= link_to 'Cancelled', jobs_path(status: 'cancelled') %>

app/views/admin/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/index.html.erb
<h1>Jobs</h1>
<%= render 'menu' %>
<div id='jobs'>
  <% if @status == 'active' || !@status.present? %>
    INBOX
    <% if @jobs.inbox.any? %>
      <% @jobs.inbox.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
    IN PROGRESS
    <% if @jobs.in_progress.any? %>
      <% @jobs.in_progress.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
  <% elsif @status == 'postponed' %>
    PAUSED
    <% if @jobs.paused.any? %>
      <% @jobs.paused.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
    ARCHIVED
    <% if @jobs.archived.any? %>
      <% @jobs.archived.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
  <% elsif @status == 'done' %>
    DONE
    <% if @jobs.done.any? %>
      <% @jobs.done.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
  <% elsif @status == 'cancelled' %>
    CANCELLED
    <% if @jobs.cancelled.any? %>
      <% @jobs.cancelled.each do |job| %>
        <%= render 'job_managers', job: job %>
      <% end %>
    <% else %>
      <p class='text-muted'>No Jobs</p>
    <% end %>
  <% end %>
</div>

app/views/admin/jobs/laundry.html.erb
<h1>Laundry </h1>
<h5>
Today/วันนี้ <%= Time.current.to_date.to_fs(:date) %>
</h5>
<div class='mt-2'>
<%= form_with(url: laundry_path, local: true, method: :get) do |f| %>
  <div class="form-row">
    <div class="col-lg-2 form-group">
      <%= date_field_tag :from, {}, value: params[:from], class: "form-control" %>
    </div>
    <div class="col-lg-2 form-group">
      <%= date_field_tag :to, {}, value: params[:to], class: "form-control" %>
    </div>
    <div class="col-lg-3 form-group">
      <%= f.submit 'Show', class: 'btn btn-primary' %>
      <%= link_to 'Drop filter', laundry_path, class: 'btn btn-secondary'  %>
    </div>
  </div>
<% end %>
</div>

<% if @error_message.present? %>
  <div class="alert alert-warning" role="alert">
    <%= @error_message %>
  </div>
<% else %>
  <div class="form-row d-none d-md-flex">
    <div class="col-md-3 form-group font-weight-bold">
      Change/เปลี่ยน
    </div>
    <div class="col-md-2 form-group font-weight-bold">
      Collect/รับ
    </div>
    <div class="col-md-2 form-group font-weight-bold">
      Send/ส่ง
    </div>
    <div class="col-md-1 form-group font-weight-bold">
      Rooms/ห้อง
    </div>
    <div class="col-md-1 form-group font-weight-bold">
      Price/ราคา
    </div>
    <div class="col-md-2 form-group font-weight-bold">
      Comment/หมายเหตุ
    </div>
  </div>
  <% ladunry_totals = {} %>
  <% @laundry.each do |l| %>
    <% house_code = l.house.code if l.house %>
    <% house_code = l.booking.house.code if l.booking %>
    <% ladunry_totals[house_code] = {qty:0, price: 0} if !ladunry_totals.key?(house_code) %>
    <% ladunry_totals[house_code][:qty] += l.rooms if !l.rooms.nil? %>
    <% ladunry_totals[house_code][:color] = 'red' if l.rooms.nil? || !l.rooms.present? || l.rooms == 0 %>
    <% ladunry_totals[house_code][:price] += l.price if !l.price.nil? %>
    <% ladunry_totals[house_code][:color] = 'red' if l.price.nil? || !l.price.present? || l.price == 0 %>
    <div class="shadow-sm mb-2 p-2 bg-white border rounded">
      <%= form_with model: l, local: true, url: update_laundry_path(l) do |f| %>
        <% if l.errors.any? %>
          <%= render 'shared/error_messages', object: f.object %>
        <% end %>
        <div class="form-row">
          <div class="col-md-3 form-group ">
            <span class='font-weight-bold'>
              <%= l.plan.to_fs(:date) %> -
              <%= l.house.code if l.house %>
              <%= l.booking.house.code if l.booking %>
              <%= l.job_type.code %>
            </span>
            <br />
            <%= l.job %>
          </div>
          <div class="col-md-2 form-group">
            <%= f.label 'Collect/รับ', class: 'd-md-none' %>
            <%= f.date_field :collected, class: 'form-control' %>
          </div>
          <div class="col-md-2 form-group">
            <%= f.label 'Send/ส่ง', class: 'd-md-none' %>
            <%= f.date_field :sent, class: 'form-control' %>
          </div>
          <div class="col-md-1 form-group">
            <%= f.label 'Rooms/ห้อง', class: 'd-md-none' %>
            <%= f.number_field :rooms, class: 'form-control' %>
          </div>
          <div class="col-md-1 form-group">
            <%= f.label 'Price/ราคา', class: 'd-md-none' %>
            <%= f.number_field :price, class: 'form-control' %>
          </div>
          <div class="col-md-2 form-group">
            <%= f.label 'Comment/หมายเหตุ', class: 'd-md-none' %>
            <%= f.text_field :comment, class: 'form-control' %>
          </div>
          <div class="col-md-1 form-group">
            <%= f.submit 'Save', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-row">
    <div class="col-md-8 form-group font-weight-bold text-right">
      Total:
    </div>
    <div class="col-md-4 form-group font-weight-bold">
      <%= @laundry.sum(:price) %>
      <% if !current_user.role? ['Maid'] %>
        <% total_sale = 0 %>
        <% ladunry_totals.each do |k, v| %>
          <br />
          <span style="color:<%= v[:color] %>">
            <%= "#{k}, #{v[:qty]} rooms = Nett #{v[:price]} / Sale #{v[:qty]*300*1.07}" %>
            <% total_sale += v[:qty]*300*1.07 %>
          </span>
        <% end %>
        <br /><span>Sale: <%= total_sale %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/show.html.erb
<h1>Job details</h1>
<%= render 'menu' %>
<%= render 'job_managers', job: @job %>
Current status: <%= @job.status %> |
Change status:
<% unless @job.status == 'in_progress' %>
  <%= link_to "In progress", job_path(@job.id, params: { job: { status: 'in_progress' } }), method: :patch %> |
<% else %>
  <%= link_to "Done", job_path(@job, params: { job: { status: 'done' } }), method: :patch %> |
  <%= link_to "Paused", job_path(@job, params: { job: { status: 'paused' } }), method: :patch %> |
<% end %>
<%= link_to "Cancelled", job_path(@job, params: { job: { status: 'cancelled' } }), method: :patch %> |
<%= link_to "Archived", job_path(@job, params: { job: { status: 'archived' } }), method: :patch %>
<div class="shadow-sm mb-2 p-2 bg-white border rounded" id="job_messages" style="overflow-y: scroll; height: 400px;">
  <% @messages.each do |m| %>
    <%= render 'job_messages/message', message: m %>
  <% end %>
  <div id="message_image" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @job.in_progress? %>
  <%= form_with(model: @message, url: job_messages_path, id: 'fileupload_message', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }) do |f| %>
    <%= hidden_field_tag 'job_id', @job.id %>
    <div class="input-group">
      <%= f.text_field :message, class: "form-control" %>
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="submit">Send</button>
        <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('fileupload_msg').click();">File</button>
      </div>
    </div>
    <input type="file" id="fileupload_msg" multiple style="display: none;">
    <div class="progress" style="height:3px;">
      <div class="progress-bar bg-info thumb" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  <% end %>
<% end %>