config/routes.rb
# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root to: 'guests/index#index'

  scope "(:locale)" do
    devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords" }
  end

  # Guests controllers
  scope "(:locale)", module: 'guests', as: 'guests', locale: /ru/ do
    root to: 'index#index', as: :locale_root
    resources :houses, only: %i[show index]
    get :about, to: 'about#index'
  end

  # Admin controllers
  scope module: 'admin' do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'report/bookings', to: 'reports#bookings'
    get 'report/balance', to: 'reports#balance'
    get 'report/salary', to: 'reports#salary'
    get 'report/income', to: 'reports#income'
    get 'reports', to: 'reports#index'
    resources :notifications, only: [:destroy]
    resources :water_usages
    get 'users/get_houses', to: 'users#get_houses' # , as: 'get_houses'
    get 'users/inactive', to: 'users#inactive'
    # get 'documents/reimbersment', to: 'documents#reimbersment', as: 'tmp_reimbersment'
    # get 'documents/statement', to: 'documents#statement', as: 'tmp_statement'
    resource :documents, only: [:show] do
      get :prepare
      get :design_agreement_preview
      get :reimbersment
      get :statement
      get :invoice
      get :receipt
    end
    resources :house_groups
    delete 'transaction_file', to: 'transaction_files#destroy'
    delete 'transaction_file_tmp', to: 'transaction_files#destroy_tmp'
    get 'transaction_file_download', to: 'transaction_files#download'
    get 'transaction_file_toggle_show', to: 'transaction_files#toggle_show'
    get 'transaction_files', to: 'transaction_files#index'
    get 'transaction_warnings', to: 'transactions#warnings'
    get 'transaction_raw_for_acc', to: 'transactions#raw_for_acc'
    get 'transaction_raw', to: 'transactions#raw'
    get 'jobs/index_new', to: 'jobs#index_new', as: 'jobs_new'
    get 'laundry', to: 'jobs#laundry', as: 'laundry'
    patch 'jobs/:id/update_laundry', to: 'jobs#update_laundry', as: 'update_laundry'
    get 'jobs/job_order', to: 'jobs#job_order', as: 'job_order'
    resources :jobs
    resources :job_types, except: :show
    post 'job_messages', to: 'job_messages#create'
    delete 'job_message', to: 'job_messages#destroy'
    get 'logs', to: 'logs#index'
    # get 'test', to: 'pages#test'
    resources :locations, except: :show
    resources :options, except: :show
    # get 'owner', to: 'admin#index', as: 'owner'
    get 'transactions/all_clients', to: 'transactions#all_clients', as: 'all_clients'
    resources :transactions, except: [:show]
    get 'transactions_docs', to: 'transactions#docs', as: 'transactions_docs'
    post 'transactions/update_invoice_ref', to: 'transactions#update_invoice_ref', as: 'update_invoice_ref'
    get 'balance', to: 'transactions#index', as: 'balance_front'
    resources :transaction_types
    get '/employees/list_for_job', to: 'employees#list_for_job'
    resources :employees
    resources :empl_types
    get '/transfers/:number/confirmed', to: 'transfers#confirmed', as: 'supplier_confirm_transfer'
    get '/transfers/:number/canceled', to: 'transfers#canceled', as: 'supplier_cancel_transfer'
    get '/transfers/supplier', to: 'transfers#index_supplier', as: 'transfers_supplier'
    resources :houses, path: 'admin_houses', as: 'admin_houses' do
      resources :prices, only: [:index]
      resources :photos, only: %i[index new destroy update] do
        put 'sort', on: :member
        delete 'delete_all', on: :collection
      end
      post 'add_duration', to: 'prices#create_duration'
      delete 'delete_duration', to: 'prices#destroy_duration'
      post 'add_season', to: 'prices#create_season'
      delete 'delete_season', to: 'prices#destroy_season'
      resources :bookings, only: %i[index new]
      get 'inactive', to: 'houses#inactive', on: :collection
      get 'export', on: :collection
    end
    post 'booking/new', to: 'bookings#create_front'
    get 'owner/bookings', to: 'bookings#index_front', as: 'bookings_front'
    resources :bookings do
      collection do
        get 'get_reservations'
        get 'get_price'
        get 'canceled'
        get 'timeline'
        get 'timeline_data'
        get 'check_in_out'
        get 'sync'
      end
      member do
        resources :booking_files, only: %i[create destroy], shallow: true
        patch 'update_comment_gr'
      end
    end
    resources :users, except: :create
    post 'create_user', to: 'users#create', as: 'create_user'
    get 'users/:id/password_reset_request', to: 'users#password_reset_request', as: 'password_reset_request'
    get 'test_upload', to: 'houses#test_upload'
    get 'prices/:id/update', to: 'prices#update', as: 'price'
    post 'prices/:house_id/copy_table', to: 'prices#copy_table', as: 'copy_table'
    # get 'owner', to: 'owner#index'
    # get 'tenant', to: 'tenant#index'
    get 'search', to: 'search#index'
    resources :settings
    resources :house_types
    resources :sources, except: :show
    resources :connections, only: %i[create destroy]
    get '/transfers/:id/cancel', to: 'transfers#cancel', as: 'cancel_transfer'
    resources :transfers
    get 'translate', to: "translations#show"
    get 'calendar/ical/:hid', to: 'bookings#ical', as: 'calendar'
  end

  get 'unlock', to: 'dev#unlock' if Rails.env.development?

  # Admin dashboards
  authenticate :user, ->(user) { user.role?('Admin') } do
    # mount GoodJob::Engine => '/admin/activejob'
    resources :uploads_tests # TODO: Remove after #353
    mount MaintenanceTasks::Engine => "/admin/maintenance_tasks"
  end

  # Errors
  match "/422", to: "errors#unprocessable_content", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*unmatched", to: "errors#not_found", via: :all, constraints: lambda { |req|
    req.path.exclude? '/files'
  }
end
# rubocop:enable

app/models/transaction_type.rb
# == Schema Information
#
# Table name: transaction_types
#
#  id             :bigint           not null, primary key
#  admin_only     :boolean          default(FALSE)
#  credit_company :boolean
#  credit_owner   :boolean
#  debit_company  :boolean
#  debit_owner    :boolean
#  name_en        :string
#  name_ru        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class TransactionType < ApplicationRecord
  has_many :transactions, dependent: :nullify, foreign_key: 'type_id'
end

app/controllers/admin/transactions_controller.rb
require 'csv'

class Admin::TransactionsController < Admin::AdminController
  before_action :set_transaction, only: %i[show edit update destroy]

  # @route GET /transactions (transactions)
  # @route GET /balance (balance_front)
  def index
    authorize!
    @from = params[:from]
    @to = params[:to]
    session[:from] = params[:from]
    session[:to] = params[:to]
    if !@from.present? && !@to.present?
      @from = Date.current.beginning_of_month
      @to = Date.current.end_of_month
    elsif !@from.present? || !@to.present?
      @error = 'Both dates should be selected'
    end

    @owner_id = params[:owner_id].present? ? params[:owner_id].to_i : nil
    @houses_count = 0
    @houses_count = User.find(@owner_id).houses.count if @owner_id.present?
    # @house_id = ['unlinked', nil].include?(params[:house_id]) ? params[:house_id] : params[:house_id].to_i
    # byebug
    # byebug
    if ["unlinked", nil].include?(params[:house_id])
      @house_id = params[:house_id]
    elsif params[:house_id].to_i > 0
      @house_id = params[:house_id].to_i
    end
    @owners = set_owners
    @houses = []
    unless @error.present?
      # Balance of company
      if @owner_id.nil? &&
         current_user.role?(%w[Admin Manager Accounting])
        # Gray balance
        if params[:commit] != 'Acc'
          @transactions        = Transaction.full(@from, @to).for_company
          @transactions_before = Transaction.before(@from)
          @transactions_by_cat = Transaction.by_cat(@from, @to)
          filter_ids           = TransactionType.find_by(name_en: 'Salary')
          if !current_user.role?(['Admin']) && filter_ids.present?
            @transactions        = @transactions.filtered(filter_ids)
            @transactions_before = @transactions_before.filtered(filter_ids)
            @transactions_by_cat = @transactions_by_cat.filtered(filter_ids)
          end
          @type = 'full'
        # White balance
        elsif params[:commit] == 'Acc'
          @transactions = Transaction.acc(@from, @to).for_company
          @transactions_before = Transaction.acc_before(@from)
          if !current_user.role?(['Admin'])
            filter_ids = TransactionType.find_by(name_en: 'Salary')
            @transactions = Transaction.acc(@from, @to).filtered(filter_ids).for_company
            @transactions_before = @transactions_before.filtered(filter_ids)
          end
          @type = 'acc'
        end
        @view = 'company'
        session.delete(:owner_id)
        session[:commit] = params[:commit]
        session[:view] = @view
      # White balance
      # Balance of selected owner
      elsif !@owner_id.nil? || current_user.role?(['Owner'])
        if current_user.role?(['Owner'])
          @owner = current_user
        # Owner view for management
        elsif current_user.role?(%w[Admin Manager Accounting])
          session[:owner_id] = @owner_id
          session[:house_id] = @house_id
          @owner = User.find(@owner_id)
        end
        @houses = @owner.houses.active.select(:id, :code)
        session[:commit] = params[:commit]
        # Gray balance (owner can see only this)
        if params[:commit] != 'Acc'
          @transactions, @transactions_before, @transactions_by_cat = owner_transactions(@owner, @from, @to, @house_id)
          type_rental_id = TransactionType.find_by(name_en: 'Rental').id
          @cr_rental = 0
          if @transactions.any?
            @cr_rental = @transactions.where(type_id: type_rental_id).joins(:balance_outs).sum(:credit)
          end
          @cr_prev_rental = 0
          if @transactions_before.any?
            @cr_prev_rental = @transactions_before.where(type_id: type_rental_id).joins(:balance_outs).sum(:credit)
          end
          @one_house = true
          @one_house = false if @owner.houses.count > 1
          today = Time.current
          future_booking_ids = @owner.houses.joins(:bookings).where('bookings.start >?', today).pluck('bookings.id')
          future_booking_de = Booking.where(id: future_booking_ids).joins(transactions: :balance_outs).sum('balance_outs.debit')
          future_booking_cr = Booking.where(id: future_booking_ids).joins(transactions: :balance_outs).sum('balance_outs.credit')
          @bookings_prepayment = future_booking_de - future_booking_cr
          @view = 'owner'
        end
        # White balance
        if params[:commit] == 'Acc' && current_user.role?(%w[Admin Manager Accounting])
          @house_id = ''
          @transactions = Transaction.full_acc_for_owner(@from, @to, @owner_id)
          @transactions_before = Transaction.before_acc_for_owner(@from, @owner_id)
          type_rental_id = TransactionType.find_by(name_en: 'Rental').id
          @view = 'accounting' if params[:commit] == 'Acc'
          session[:view] = @view
        end
      end
    end
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=transactions.csv"
      end
    end
  end

  # @route GET /transactions/all_clients (all_clients)
  def all_clients
    authorize!
    @from = params[:from]
    @to = params[:to]
    if !@from.present? && !@to.present?
      @from = Date.current.beginning_of_month
      @to = Date.current.end_of_month
    elsif !@from.present? || !@to.present?
      @error = 'Both dates should be selected'
    end
    group_id = params[:house_group_id]
    # @owner = User.find(params[:view_user_id])
    # @one_house = true
    # @one_house = false if @owner.houses.count > 1
    @transactions = Transaction.joins(:balance_outs, :house)
                                .preload(:house, :user)
                                .where(transactions: {date: @from..@to, for_acc: false})
                                .yield_self { |q| group_id.present? ? q.where(houses: { house_group_id: group_id }) : q }
                                .select('transactions.*, COALESCE(SUM(balance_outs.debit), 0)  AS debit, COALESCE(SUM(balance_outs.credit), 0) AS credit')
                                .group('transactions.id')
                                .order(:date, :created_at).all
  end 

  def show
    authorize!
  end

  # @route GET /transactions_docs (transactions_docs)
  def docs
    authorize!
    @from = params[:from]
    @to = params[:to]
    @owner = User.find(params[:view_user_id])
    @one_house = true
    @one_house = false if @owner.houses.count > 1
    @transactions = Transaction.where('date >= ? AND date <= ? AND user_id = ?', @from, @to, @owner.id).order(:date,
                                                                                                              :created_at).all
    if params[:type] == 'invoice'
      render template: 'admin/transactions/invoice'
    elsif params[:type] == 'receipt'
      render template: 'admin/transactions/receipt'
    end
  end

  # @route GET /transactions/new (new_transaction)
  def new
    authorize!
    if params[:tid].present?
      tid = params[:tid]
      old_transaction = Transaction.find(tid)
      @transaction = old_transaction.dup
      @transaction.date = nil
      @de_ow = old_transaction.balance_outs.sum(:debit)
      @cr_ow = old_transaction.balance_outs.sum(:credit)
      @de_co = old_transaction.balances.sum(:debit)
      @cr_co = old_transaction.balances.sum(:credit)
      @cr_ow -= @de_co
    else
      @transaction = Transaction.new
    end
    # now = Time.current
    @s3_direct_post = S3_BUCKET.presigned_post(
      key: "transactions/${filename}",
      success_action_status: '201',
      acl: 'public-read',
      content_type_starts_with: ""
    )
    if params[:user_id].present?
      owner = User.find(params[:user_id])
      @transaction.user_id = owner.id
      @transaction.house_id = owner.houses.first.id if owner.houses.count == 1
      if params[:house_id].present? && (params[:house_id].to_i > 0)
        @house = House.find(params[:house_id])
        @transaction.house_id = @house.id
      end
      @bookings = owner.unpaid_bookings
    else
      @bookings = Booking.unpaid
    end
  end

  # @route GET /transactions/:id/edit (edit_transaction)
  def edit
    authorize! @transaction
    @de_ow = @transaction.balance_outs.sum(:debit)
    @cr_ow = @transaction.balance_outs.sum(:credit)
    @de_co = @transaction.balances.sum(:debit)
    @cr_co = @transaction.balances.sum(:credit)
    @bookings = []
    @s3_direct_post = S3_BUCKET.presigned_post(
      key: "transactions/${filename}",
      success_action_status: '201',
      acl: 'public-read',
      content_type_starts_with: ""
    )
    if @transaction.user
      owner = @transaction.user
      @bookings = owner.unpaid_bookings(@transaction.booking_id)
    end
  end

  # @route POST /transactions (transactions)
  def create
    authorize!
    @transaction = Transaction.new(transaction_params)
    @transaction.set_owner_and_house
    respond_to do |format|
      if @transaction.save
        de_ow = params[:transaction][:de_ow].to_d
        cr_ow = params[:transaction][:cr_ow].to_d
        de_co = params[:transaction][:de_co].to_d
        cr_co = params[:transaction][:cr_co].to_d
        type = TransactionType.find(params[:transaction][:type_id]).name_en
        @transaction.write_to_balance(type, de_ow, cr_ow, de_co, cr_co)
        files = params['transaction']['files']
        unless files.nil?
          files.each do |f|
            @transaction.files.create!(url: f)
          end
        end
        files_to_show = params['transaction']['files_to_show']
        unless files_to_show.nil?
          files_to_show.each do |f|
            @transaction.files.find_by(url: f).update(show: true)
          end
        end
        if @transaction.errors.any?
          @transaction.destroy
          if params[:user_id].present?
            owner = User.find(params[:user_id])
            @transaction.user_id = owner.id

app/views/admin/transactions/_owner_accounting_view.html.erb
<div class="d-none d-print-block">
  Balance of: <%= "#{@owner.name} #{@owner.surname}" %>
  <br />
  Address:
  <% @owner.houses.each do |h| %>
    - <%= h.address %><br />
  <% end %>
</div>
<table class='table table-striped table-bordered table-sm bg-white'>
  <thead>
    <tr>
      <th width="55px">Date</th>
      <th width="250px">Ref No</th>
      <th class="text-right" width="90px">Debit</th>
      <th class="text-right" width="90px">Credit</th>
      <th class="text-right" width="90px">Balance</th>
      <th>Comment</th>
      <th class="d-print-none">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% de_ow_sum = 0 %>
    <% cr_ow_sum = 0 %>
    <% de_co_sum = 0 %>
    <% de_ow_prev_sum = 0 %>
    <% cr_ow_prev_sum = 0 %>
    <% balance_sum = 0 %>
    <% if transactions_before.any? %>
      <% de_ow_prev_sum = transactions_before.joins(:balance_outs).sum('balance_outs.debit') %>
      <% cr_ow_prev_sum = transactions_before.joins(:balance_outs).sum('balance_outs.credit') %>
      <% balance_sum += de_ow_prev_sum - cr_ow_prev_sum %>
      <tr>
        <td></td>
        <td></td>
        <td class="text-right" id="de_ow_prev_sum">
        </td>
        <td class="text-right" id="cr_ow_prev_sum">
        </td>
        <td class="text-right" id="ow_prev_balance">
          <%= number_to_currency(balance_sum, precision: 2, unit: '') %>
        </td>
        <td>Balance from previous period</td>
        <td class="d-print-none"></td>
      </tr>
    <% end %>
    <% transactions.each do |t| %>
      <% de_ow = t.balance_outs.sum(:debit) %>
      <% cr_ow = t.balance_outs.sum(:credit) %>
      <% de_co = t.balances.sum(:debit) %>
      <% cr_co = t.balances.sum(:credit) %>
      <% cr_ow_personal = cr_ow - de_co  %>
      <% de_ow_sum += de_ow %>
      <% cr_ow_sum += cr_ow_personal %>
      <% de_co_sum += de_co %>
      <% balance_sum += de_ow - cr_ow_personal %>
      <% next if (cr_ow - de_co + de_ow ) == 0 %>
      <tr id="trsc_<%= t.id %>_row"
        <%= 'class=for_acc_row' if t.for_acc %>>
        <td><span style="display:none;"><%= t.date.to_time.to_i %></span><%= t.date.to_fs(:date) %></td>
        <td><small>
            <%= t.ref_no %></small></td>
        <td class='de_ow_cell text-right'>
          <%= number_to_currency(de_ow, precision: 2, unit: '') if de_ow > 0 %>
        </td>
        <td class='cr_ow_cell text-right'>
          <%= number_to_currency(cr_ow_personal, precision: 2, unit: '') if cr_ow_personal > 0 %>
        </td>
        <td class='balance_sum_cell text-right'>
          <%= number_to_currency(balance_sum, precision: 2, unit: '') if !t.hidden %>
        </td>
        <td class='comment'><%= t.comment_en %><%= t.cash ? " /C" : nil %></td>
        <td class="d-print-none">
          <% if current_user.role?(['Accounting', 'Manager']) && t.date > (Date.current-30.days).beginning_of_month %>
            <%= link_to 'Edit', edit_transaction_path(t) %>
            <% if de_ow > 0 %>
              <%= link_to 'ST', statement_documents_path(trsc_id: t.id), target: '_blank' %>
              <%= link_to 'RB', reimbersment_documents_path(trsc_id: t.id), target: '_blank' %>
            <% end %>
          <% end %>
          <% if current_user.role?(['Accounting', 'Manager']) && t.date > Date.current-1.day %>
            <%= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <% if current_user.role?('Admin') %>
            <%= link_to 'Edit', edit_transaction_path(t) %>
            <%= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% if de_ow > 0 %>
              <%= link_to 'ST', statement_documents_path(trsc_id: t.id), target: '_blank' %>
              <%= link_to 'RB', reimbersment_documents_path(trsc_id: t.id), target: '_blank' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% if de_co_sum > 0 %>
      <% cr_ow_sum += de_co_sum %>
      <tr>
        <td><%= @to.to_date.to_fs(:date) %></td>
        <td>
          <small>
            <% ref_no = transactions.joins(:balances).where('balances.debit > 0').pluck('balances.ref_no').uniq.join(', ') %>
            <% ref_no = transactions.joins(:balance_outs).where('balance_outs.credit > 0').pluck('balance_outs.ref_no').uniq.join(', ') if ref_no.empty? %>
            <%= ref_no %>
          </small>
        </td>
        <td></td>
        <td class='text-right' id='company_maintenance'><%= number_to_currency(de_co_sum, precision: 2, unit: '') %></td>
        <td class='balance_sum_cell text-right'><%= number_to_currency(balance_sum - de_co_sum, precision: 2, unit: '') %></td>
        <td>Maintenance</td>
        <td class="d-print-none">
          <% if @from.to_date.month == @to.to_date.month %>
            <%= link_to 'Invoice', transactions_docs_path(
              type: 'invoice', from: @from, to: @to, view_user_id: @owner_id), target: '_blank' %>
            <%= link_to 'Receipt', transactions_docs_path(
              type: 'receipt', from: @from, to: @to, view_user_id: @owner_id), target: '_blank' %>
          <% else %>
            <span class="text-muted">Invoice</span>
            <span class="text-muted">Receipt</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr class="d-print-none">
      <td></td>
      <td class='font-weight-bold text-right d-print-none'>Total:</td>
      <td class="font-weight-bold text-right d-print-none">
        <div id='de_ow_sum'>
          <%= number_to_currency(de_ow_sum, precision: 2, unit: '') %>
        </div>
      </td>
      <td class="font-weight-bold text-right d-print-none">
        <div id='cr_ow_sum'>
          <%= number_to_currency(cr_ow_sum, precision: 2, unit: '') %>
        </div>
      </td>
      <td class="font-weight-bold text-right d-print-none">
        <div id="ow_balance">
          <%= number_to_currency(de_ow_prev_sum + de_ow_sum - cr_ow_prev_sum - cr_ow_sum, precision: 2, unit: '') %>
        </div>
      </td>
      <td></td>
      <td>
      </td>
    </tr>
  </tfoot>
</table>
<% disabled = false %>
<% if @from.to_date.month != @to.to_date.month %>
  <% disabled = true %>
<% end %>
<%= form_with(url: update_invoice_ref_path, local: false, class: 'form-inline d-print-none') do |f| %>
  <%= text_field_tag 'ref_no', nil, class: 'form-control mr-2 w-50', placeholder: 'Ref no.', disabled: disabled %>
  <%= f.submit 'Save', class: 'btn btn-primary', disabled: disabled %>
<% end %>
<%= link_to 'ST', statement_documents_path(owner_id: @owner.id), target: '_blank', class: 'd-print-none' %>
<% if current_user.role?('Admin') %>
  <%= link_to 'RAW INCOME', transaction_raw_for_acc_path(
      from: @from,
      to: @to,
      owner_id: @owner_id,
      house_id: @house_id
    ), target: '_blank', class: 'd-print-none' %>
<% end %>

app/views/admin/transactions/all_clients.erb
<h1><%= t('balance') %></h1>
  <%= form_with(url: all_clients_path, method: :get, local: true, class: 'd-print-none') do |form| %>
    <div class="form-row mb-2">
      <div class="col-6 col-lg-2">
        <%= date_field_tag :from, {}, value: @from, class: "form-control" %>
      </div>
      <div class="col-6 col-lg-2">
        <%= date_field_tag :to, {}, value: @to, class: "form-control mb-2 mr-md-2" %>
      </div>
      <div class="col-6 col-lg-2">
        <%= select_tag :house_group_id, options_from_collection_for_select(HouseGroup.all.order(:name), :id, :name, params[:house_group_id]), include_blank: t('select_house_group'), class: "form-control mb-2 mr-md-2" %>
      </div>
      <div class="form-row col-12 col-lg-4 mt-2 mt-lg-0">
        <div class="col-6">
          <%#= hidden_field_tag :owner_id, @owner.id %>
          <%= submit_tag t('show'), class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>
  <% end %>
  <% if @error %>
    <div class="alert alert-warning" role="alert">
      <%= @error %>
    </div>
  <% else %>
    <div class="table-responsive">
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th class="col-1"><%= t('date_text') %></th>
            <th class="col-1"><%= t('debit') %></th>
            <th class="col-1"><%= t('credit') %></th>
            <th class="col-3"><%= t('owner') %></th>
            <th class="col-1"><%= t('house') %></th>
            <th><%= t('comment') %></th>
          </tr>
        </thead>
        <tbody>
          <% @transactions.each do |t| %>
            <tr>
              <td><%= t.date.strftime('%d.%m.%Y') %></td>
              <td class="text-right"><%= number_to_currency(t.debit, unit: '') %></td>
              <td class="text-right"><%= number_to_currency(t.credit, unit: '') %></td>
              <td><%= "#{t.user&.name} #{t.user&.surname}" %></td>
              <td><%= t.house&.code %></td>
              <td><%= t.comment_en %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th><%= t('total') %></th>
            <th class="text-right"><%= number_to_currency(@transactions.sum { |t| t.debit.to_d }, unit: '') %></th>
            <th class="text-right"><%= number_to_currency(@transactions.sum { |t| t.credit.to_d }, unit: '') %></th>
            <th colspan="3"></th>
          </tr>
        </tfoot>
      </table>
    </div>
  <% end %>

app/views/admin/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

app/views/admin/transactions/index_front.html.erb
<h1><%= t('balance') %></h1>

<%= form_with(url: balance_path, method: :get, local: true, class: 'form-inline d-print-none') do |form| %>
      <%= date_field_tag :from, {}, value: @from, class: "form-control mb-2 mr-md-2" %>
      <%= date_field_tag :to, {}, value: @to, class: "form-control mb-2 mr-md-2" %>
      <%= submit_tag t('show'), class: "btn btn-primary mb-2 mr-2" %>
      <%= link_to t('drop_filter'), balance_front_path, class: 'btn btn-secondary mb-2 mr-md-2'  %>
<% end %>

<%= render 'owner_view', {transactions: @transactions, transactions_before: @transactions_before, one_house: @one_house} %>

app/views/admin/transactions/new.html.erb
<h1>
  New Transaction
</h1>
<h5>
  <% if @transaction.user_id  %>
    <% u = User.find(@transaction.user_id) %>
    <%= "Owner: #{u.code} (#{u.name} #{u.surname})" %>
    <%= "/ House: #{House.find(@transaction.house_id).code}" if @transaction.house_id %>
  <% end %>
</h5>

<%= render 'form', transaction: @transaction %>

app/views/admin/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ref no:</strong>
  <%= @transaction.ref_no %>
</p>

<p>
  <strong>House:</strong>
  <%= @transaction.house_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @transaction.type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user_id %>
</p>

<p>
  <strong>Comment en:</strong>
  <%= @transaction.comment_en %>
</p>

<p>
  <strong>Comment ru:</strong>
  <%= @transaction.comment_ru %>
</p>

<p>
  <strong>Comment inner:</strong>
  <%= @transaction.comment_inner %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>